apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.app.name }}
  type: NodePort

